version: 2

models:
  - name: stg_localbike__brands
    description: "This model contains information about brands aka id and name "
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brands: brand_id"
        tests:
            - unique
            - not_null


  - name: stg_localbike__categories
    description: "This model contains information about categories aka id and name "
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
            - unique
            - not_null
      - name: category_name
        description: "The current name of the categories."
        tests:
          - accepted_values:
              arguments:
               name: accepted_values_category_name
               values: ['Children Bicycles', 'Comfort Bicycles', 'Cruisers Bicycles', 'Cyclocross Bicycles', 'Electric Bikes', 'Mountain Bikes', 'Road Bikes']


  - name: stg_localbike__customers
    description: "This model contains information about each customers, included name, adress, email and phone number (sometimes, we don't need really)."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null
            - relationships:
               arguments:
                name: customer_id_id_foreign_key_in_stg_localbike__customers
                to: ref('stg_localbike__orders')
                field: customer_id
     

  - name: stg_localbike__order_items 
    description: "This model contains information about each item included in an order, including its price, quantity, and discount."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item. It is the combinaison of order_id and item_id"
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              arguments:
                name: order_id_id_foreign_key_in_stg_localbike__order_items
                to: ref('stg_localbike__orders')
                field: order_id
      - name: product_id
        description: "Foreign key linking the order item to the corresponding product."
        tests:
          - relationships:
              arguments:
                name: product_id_id_foreign_key_in_stg_sales_database__order_item
                to: ref('stg_localbike__products')
                field: product_id
      - name: total_order_item_amount_discount
        description: "The total amount for this order item with discount, calculated : list_price * ( 1 - discount) * quantity."
      - name: total_order_item_amount_no_discount
        description: "The total amount for this order item without discount, calculated : quantity * list_price ."

  - name: stg_localbike__orders
    description: "This model contains information about orders placed by users, including the status of each order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: order_status
        description: "The current status of the order."
        tests:
          - accepted_values:
              arguments:
               name: accepted_values_order_status
               values: [1,2,3,4]
               quote: false
      - name: customer_id
        description: "Foreign key linking the order to the user who placed it."
        tests:
          - relationships:
              arguments:
                name: customer_id_id_foreign_key_in_stg_localbike__orders
                to: ref('stg_localbike__customers')
                field: customer_id
      - name: staff_id
        description: "Foreign key linking the order to the staff who placed it."
        tests:
          - relationships:
              arguments:
                name: staff_id_id_foreign_key_in_stg_localbike__orders
                to: ref('stg_localbike__staffs')
                field: staff_id
      - name: store_id
        description: "Foreign key linking the order to the store who placed it."
        tests:
          - relationships:
              arguments:
                name: store_id_id_foreign_key_in_stg_localbike__orders
                to: ref('stg_localbike__stores')
                field: store_id

  - name: stg_localbike__products
    description: "This model contains details of products available for sale, primarily focusing on information about the product's brand, category and price."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the product to the brand with which it is associated."
        tests:
            - not_null
            - relationships:
               arguments:
                name: brand_id_id_foreign_key_in_stg_localbike__products
                to: ref('stg_localbike__brands')
                field: brand_id
      - name: category_id
        description: "Foreign key linking the product to the category with which it is associated."
        tests:
            - not_null
            - relationships:
               arguments:
                name: category_id_id_foreign_key_in_stg_localbike__products
                to: ref('stg_localbike__categories')
                field: category_id

  - name: stg_localbike__staff
    description: "This model contains information about the staffs who provide the products."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each seller."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the seller to the store where they work."
        tests:
            - not_null
            - relationships:
               arguments:
                name: store_id_id_foreign_key_in_stg_localbike__staff
                to: ref('stg_localbike__stores')
                field: store_id

  - name: stg_localbike__stocks
    description: "This model contains stocks informations."
    columns:
      - name: store_product_id
        description: "Primary key, unique identifier for each store, each product."
        tests:
            - unique
            - not_null                

  - name: stg_localbike__stores
    description: "This model contains stores-related information, including the address, email and phone."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each stores."
        tests:
            - unique
            - not_null      